name: DomnianIRC
main: com.domnian.DomnianIRC.DomnianIRC
author: willies952002
version: 0.5

commands:
  irc:
    usage: /irc [join|list|quit|connect] [channel]
    description: Command for Controlling the IRC Bot
    permission: domnian.irc
    permission-message: You are not allowed to control the IRC Bot